let db = {
    // document id = auto generated
    screams:[
        {
            userHandle: 'username',
            body: 'contents of scream',
            createdAt: '2020-08-01T03:06:39.714Z',
            nLike: 5,
            nComment: 7,
        }
    ],
    // document id = userHandle
    users:[
        {
            userId: 'autogeneratedId',
            createdAt: 'contents of scream',
            emailId: '2020-08-01T03:06:39.714Z',
            userHandle: "facinick"
        }
    ]
}